### ISSUE TITLE
Add unregister command to remove the auth token

### ISSUE THREAD

**Issue by julien-f** [vatesfr/xo-cli#10]

**Comment by AbbyNormal** [comment]
Hi. Is there a way to delete it manually or through xo-cli? Maybe:

token.create
  create a new authentication token
token.delete token=<string>
  delete an existing authentication token

How to find the existing token string?

**Comment by julien-f** [comment]
Are you on Linux? If so, you can delete `~/.config/xo-cli/config.json` :)

**Comment by AbbyNormal** [comment]
Yes, Linux. Tnx :)

**Comment by julien-f** [comment]
`--unregister` exists, it was just undocumented.
