### ISSUE TITLE
Filter options

### ISSUE THREAD

**Issue by multihost** [vatesfr/xo-cli#18]
Hi,

First of all - great project!

I am missing some more filter options on "--list-objects".

It would for example been great if I could filter the print on name-label from UUID, and UUID from name-label.

And some filter so print UUID of network out of name-label.

**Comment by julien-f** [comment]
So, what you need is a way to select which properties are displayed for the list of objects?

**Comment by multihost** [comment]
Hei,

Denne meldingen er autogenerert som en respons til din henvendelse angående:
"{Disarmed} Re: [vatesfr/xo-cli] Filter options (#18)".

Du trenger ikke svare på denne meldingen akkurat nå.
Din henvendelse har fått ID'en [MultiHost IT #16247].

Vennligst inkluder [MultiHost IT #16247] i tittelen/subject 
av en email når du svarer til support om denne henvendelsen.
                 
Med vennlig hilsen,
Multihost IT Support

post@multihost.no
-------------------------------------------------------------------------

So, what you need is a way to select which properties are displayed for the list of objects?

**Comment by multihost** [comment]
Hi,

Yes, for example if I want to know what the UUID of "vlan50" is, i could for example have used this:

xo-cli --list-objects type=network name-label=vlan50 get=uuid
= print UUID

The same for getting UUID of the actual VM and parhaps disks VDIs

**Comment by multihost** [comment]
I might have solved it with:

<?

$objarr = shell_exec('xo-cli --list-objects');
$objarr = json_decode($objarr, true);

foreach($objarr as $obj){

        if($obj['name_label'] == "vlan50"){
                echo $obj['uuid'];
        }
}

**Comment by julien-f** [comment]
Released as v0.8.1:

```
xo-cli --list-objects [--<property>]… [<property>=<value>]...
  Returns a list of XO objects.

  --<property>
    Restricts displayed properties to those listed.

  <property>=<value>
    Restricted displayed objects to those matching the patterns.
```

**Comment by multihost** [comment]
Hei,

Denne meldingen er autogenerert som en respons til din henvendelse angående:
"{Disarmed} Re: [vatesfr/xo-cli] Filter options (#18)".

Du trenger ikke svare på denne meldingen akkurat nå.
Din henvendelse har fått ID'en [MultiHost IT #16248].

Vennligst inkluder [MultiHost IT #16248] i tittelen/subject 
av en email når du svarer til support om denne henvendelsen.
                 
Med vennlig hilsen,
Multihost IT Support

post@multihost.no
-------------------------------------------------------------------------

Released as v0.8.1:

```
xo-cli --list-objects [--<property>]… [<property>=<value>]...
  Returns a list of XO objects.

  --<property>
    Restricts displayed properties to those listed.

  <property>=<value>
    Restricted displayed objects to those matching the patterns.
```

**Comment by multihost** [comment]
Hei,

Denne meldingen er autogenerert som en respons til din henvendelse angående:
"{Disarmed} Re: [vatesfr/xo-cli] Filter options (#18)".

Du trenger ikke svare på denne meldingen akkurat nå.
Din henvendelse har fått ID'en [MultiHost IT #16249].

Vennligst inkluder [MultiHost IT #16249] i tittelen/subject 
av en email når du svarer til support om denne henvendelsen.
                 
Med vennlig hilsen,
Multihost IT Support

post@multihost.no
-------------------------------------------------------------------------

Closed #18 via 987b7ce9a254a629d8c1fc6a39e696a4aedabc2b.

-- 
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/vatesfr/xo-cli/issues/18#event-870975785
