### ISSUE TITLE
Listing all VMs

### ISSUE THREAD

**Issue by DaveWoodman** [vatesfr/xo-cli#8]
Please provide a command to list all VMs - currently the only way appears to be to filter the results of xo.getAllObjects.

**Comment by julien-f** [comment]
What is your use case?

Because xo-cli is mainly used as a handy test tool, if you really want to use the full power of the API I suggest you develop your own script based on [xo-lib](/vatesfr/xo-lib) which provides a higher level interface.

**Comment by DaveWoodman** [comment]
My wish was to use this from within Rundeck (rundeck,org). The environment has direct support for shell (thus xo-cli) and for Java.

**Comment by julien-f** [comment]
Do not expect great performances, all objects are downloaded each time.

**Comment by DaveWoodman** [comment]
I don't expect much in the way of speed - just a little automation!

**Comment by olivierlambert** [comment]
Could you test on your side and tell us if that's ok?

**Comment by DaveWoodman** [comment]
I have tested - and it will do exactly what I need. A nice general-purpose solution! Thank you

**Comment by olivierlambert** [comment]
\o/
